server:
  port: 8091

spring:
  # application.name: 'book-ms'
#  database configurations::begin
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookDB}
    username: ${SPRING_DATASOURCE_USERNAME:postgresql}
    password: ${SPRING_DATASOURCE_USERNAME:postgresql}
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/migration/db.changelog-master.xml
#  database configurations::end

# service discovery client configs::begin
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
# service discovery client configs::end


springdoc:
  api-docs:
    enabled: true
#  show-actuator: true

